/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalbim1;

/**
 *
 * @author Usuario
 */
public class CalificarSeviiciop2 extends javax.swing.JFrame {

    /**
     * Creates new form CalificarSeviiciop2
     */
    public static String respt = "";
    public static  String n2;

    public CalificarSeviiciop2() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnSiguiente.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opciones = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        jrBtn1 = new javax.swing.JRadioButton();
        jrBtn2 = new javax.swing.JRadioButton();
        jrBtn3 = new javax.swing.JRadioButton();
        jrBtn4 = new javax.swing.JRadioButton();
        btnSiguiente = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Pregunta Nro 2");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 28, -1, -1));

        lblPregunta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPregunta.setForeground(new java.awt.Color(0, 0, 0));
        lblPregunta.setText("La manera de la atencion del chofer fue :");
        getContentPane().add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 70, 290, 26));

        Opciones.add(jrBtn1);
        jrBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrBtn1.setText("Muy Bueno");
        jrBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jrBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        Opciones.add(jrBtn2);
        jrBtn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrBtn2.setText("Bueno");
        jrBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jrBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 70, -1));

        Opciones.add(jrBtn3);
        jrBtn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrBtn3.setText("Regular");
        jrBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jrBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        Opciones.add(jrBtn4);
        jrBtn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrBtn4.setText("Malo");
        jrBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jrBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        btnSiguiente.setBackground(new java.awt.Color(255, 0, 0));
        btnSiguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 327, 120, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/fondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:

      
        this.setVisible(false);
        CalificarServiciop3 cs3 = new CalificarServiciop3();
        cs3.setVisible(true);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void jrBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrBtn1ActionPerformed
        // TODO add your handling code here:
        respt = "Muy Bueno";
          n2="4";
          btnSiguiente.setEnabled(true);
    }//GEN-LAST:event_jrBtn1ActionPerformed

    private void jrBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrBtn2ActionPerformed
        // TODO add your handling code here:
        respt= "Bueno";
          n2="3";
          btnSiguiente.setEnabled(true);
    }//GEN-LAST:event_jrBtn2ActionPerformed

    private void jrBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrBtn3ActionPerformed
        // TODO add your handling code here:
         respt= "Regular";
          n2="2";
          btnSiguiente.setEnabled(true);
    }//GEN-LAST:event_jrBtn3ActionPerformed

    private void jrBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrBtn4ActionPerformed
        // TODO add your handling code here:
         respt= "Malo";
          n2="1";
          btnSiguiente.setEnabled(true);
    }//GEN-LAST:event_jrBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalificarSeviiciop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalificarSeviiciop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalificarSeviiciop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalificarSeviiciop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalificarSeviiciop2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Opciones;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JRadioButton jrBtn1;
    private javax.swing.JRadioButton jrBtn2;
    private javax.swing.JRadioButton jrBtn3;
    private javax.swing.JRadioButton jrBtn4;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
