/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalbim1;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CalificarServiciop3 extends javax.swing.JFrame {

    /**
     * Creates new form CalificarServiciop3
     */
    public static String respta = "";
    public static String n3;
    public CalificarServiciop3() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnSiguiente.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpciones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrBtn1 = new javax.swing.JRadioButton();
        jrBtn2 = new javax.swing.JRadioButton();
        jrBtn3 = new javax.swing.JRadioButton();
        jrBtn4 = new javax.swing.JRadioButton();
        btnSiguiente = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pregunta Nro 3");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Como  fue la experiencia que usted obtuvo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, 320, 27));

        bgOpciones.add(jrBtn1);
        jrBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrBtn1.setText("Muy Bueno");
        jrBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jrBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 103, -1, -1));

        bgOpciones.add(jrBtn2);
        jrBtn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrBtn2.setText("Bueno");
        jrBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jrBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 144, 80, -1));

        bgOpciones.add(jrBtn3);
        jrBtn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrBtn3.setText("Regular");
        jrBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jrBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 193, 80, -1));

        bgOpciones.add(jrBtn4);
        jrBtn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrBtn4.setText("Malo");
        jrBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jrBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 234, 80, -1));

        btnSiguiente.setBackground(new java.awt.Color(255, 0, 0));
        btnSiguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 120, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/fondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
         
       
        this.setVisible(false);
        CalificarServiciop4 cs4 = new CalificarServiciop4();
        cs4.setVisible(true);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void jrBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrBtn1ActionPerformed
        // TODO add your handling code here:
        respta = "Muy Bueno";   
          n3="4";
          
          btnSiguiente.setEnabled(true);
    }//GEN-LAST:event_jrBtn1ActionPerformed

    private void jrBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrBtn2ActionPerformed
        // TODO add your handling code here:
        respta = "Bueno";   
          n3="3";
          
          btnSiguiente.setEnabled(true);
    }//GEN-LAST:event_jrBtn2ActionPerformed

    private void jrBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrBtn3ActionPerformed
        // TODO add your handling code here:
        respta = "Regular";   
          n3="2";
          
          btnSiguiente.setEnabled(true);
    }//GEN-LAST:event_jrBtn3ActionPerformed

    private void jrBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrBtn4ActionPerformed
        // TODO add your handling code here:
        respta = "Muy Bueno";   
          n3="1";
          
          btnSiguiente.setEnabled(true);
    }//GEN-LAST:event_jrBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalificarServiciop3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalificarServiciop3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalificarServiciop3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalificarServiciop3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalificarServiciop3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpciones;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jrBtn1;
    private javax.swing.JRadioButton jrBtn2;
    private javax.swing.JRadioButton jrBtn3;
    private javax.swing.JRadioButton jrBtn4;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
