/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalbim1;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.io.File;

import javax.swing.JOptionPane;


public class LectorCodigo extends javax.swing.JFrame {

    private Dimension ds = new Dimension(450, 360);
    private Dimension cs = WebcamResolution.VGA.getSize();
    private Webcam wCam = Webcam.getDefault();
    private WebcamPanel wCamPanel = new WebcamPanel(wCam, ds, false);
     //Metodo para bloquear el boton de calificar

    public void Bloquear() {
        btnSiguiente.setEnabled(false);
    }
    //Metodo para desbloquear el boton de calificar

    public void Desbloquear() {
        btnSiguiente.setEnabled(true);
    }
    //Metodo para buscar en los datos registrados  y para habilitar o desahbilitar el boton siguiente

  public void mostrar() {
        Registro_CodigoQR rcqr = new Registro_CodigoQR();
        File url = new File(rcqr.ubicacion + txtLector.getText() + ".txt");
        if (url.exists()) {
            Desbloquear();
            
        } else {
            Bloquear();
            JOptionPane.showMessageDialog(rootPane, "Registro no exitente");
        }

    }
public static String val ="";
    public LectorCodigo() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtLector.setEditable(true);
        wCam.setViewSize(cs);
        wCamPanel.setFillArea(true);
        jpCam.setLayout(new FlowLayout());
        jpCam.add(wCamPanel);
        Thread t = new Thread() {
            @Override
            public void run() {
                wCamPanel.start();
                      Bloquear();
                do {

                    Result result = null;
                    BufferedImage image = null;

                    if (wCam.isOpen()) {

                        if ((image = wCam.getImage()) == null) {
                            continue;
                        }

                        LuminanceSource source = new BufferedImageLuminanceSource(image);
                        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

                        try {
                            result = new MultiFormatReader().decode(bitmap);
                        } catch (NotFoundException e) {
                            // fall thru, it means there is no QR code in image
                        }
                    }

                    if (result != null) {

                        txtLector.setText(result.getText());
                        mostrar();
                        val=txtLector.getText();
                    }

                } while (true);
                  
            
            }
            

        };
        
        t.setDaemon(true);
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCam = new javax.swing.JPanel();
        txtLector = new javax.swing.JTextArea();
        btnSiguiente = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpCam.setBackground(new java.awt.Color(0, 0, 0));
        jpCam.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpCamLayout = new javax.swing.GroupLayout(jpCam);
        jpCam.setLayout(jpCamLayout);
        jpCamLayout.setHorizontalGroup(
            jpCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jpCamLayout.setVerticalGroup(
            jpCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(jpCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 400, 350));

        txtLector.setColumns(20);
        txtLector.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtLector.setRows(5);
        getContentPane().add(txtLector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 60));

        btnSiguiente.setBackground(new java.awt.Color(0, 255, 0));
        btnSiguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setText("CALIFICAR");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 40));

        btnVolver.setBackground(new java.awt.Color(255, 255, 0));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 110, 40));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btn_cerrar2.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 40, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/fondo.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CalificarServicio cals = new CalificarServicio();
        cals.setVisible(true);
        wCamPanel.stop();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Bienvenida bn = new Bienvenida();
        bn.setVisible(true);
        wCamPanel.stop();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LectorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LectorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LectorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LectorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LectorCodigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jpCam;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextArea txtLector;
    // End of variables declaration//GEN-END:variables
}
